global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'auth_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8000']
